import Head from "next/head";
import Link from "next/link";

import Header from "../components/Header";
import Footer from "../components/Footer";
import Socials from "../components/Socials";
import Languages from "../components/Languages";
import Libraries from "../components/Libraries";
import Frameworks from "../components/Frameworks";
import Tools from "../components/Tools";
import SkillTemplate from "../components/SkillTemplate";

export default function Home() {
  return (
    <div className="bg-zinc-900 min-h-screen">
      <Head>
        <title>Shane Le</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      {/* Hero Section */}
      <div className="py-4 md:pt-8 mt-24 rounded-lg space-y-5 grid-cols-1 max-w-xs sm:max-w-md md:max-w-2xl xl:max-w-6xl mx-auto">
        <div className="text-white font-semibold px-5 mb-8 text-center space-y-10">
          <h1 className="text-2xl md:text-4xl text-center">Hallo!</h1>
          <p className="text-lg md:text-xl">
            I’m Shane, a Front End Developer based in a small-town in Norway.
          </p>
        </div>
        <div>
          <div className="flex items-center justify-center space-x-6 py-2 md:py-5">
            {Socials?.map((social) => (
              <div
                key={social.id}
                className="text-rose-600 hover:text-rose-800 pb-3"
              >
                <Link href={social.path} passHref>
                  <a className="text-3xl md:text-5xl" target="_blank">
                    {social.icon}
                  </a>
                </Link>
              </div>
            ))}
          </div>
        </div>
      </div>
      {/* Skills & Tools Section */}
      <h1 className="text-rose-600 text-center font-semibold text-2xl pt-6 sm:pt-12">
        Skills & Tools
      </h1>
      <div className="sm:grid grid-cols-3 gap-4 md:max-w-4xl lg:max-w-7xl pt-3 pb-12  mx-auto">
        <section className="container flex flex-col items-center">
          <h2 className="text-white text-center py-4 sm:py-8">
            Programing Languages
          </h2>
          <div className="grid grid-cols-4 gap-4 md:grid-cols-3">
            {Languages?.map((language) => (
              <SkillTemplate
                key={language.id}
                icon={language.icon}
                skillName={language.name}
              />
            ))}
          </div>
        </section>

        <section className="container flex flex-col items-center">
          <h2 className="text-white text-center py-4 sm:py-8">
            Libraries & Frameworks
          </h2>
          <div className="grid grid-cols-4 gap-4 md:grid-cols-3">
            {Libraries?.map((library) => (
              <SkillTemplate
                key={library.id}
                icon={library.icon}
                skillName={library.name}
              />
            ))}
            {Frameworks?.map((framework) => (
              <SkillTemplate
                key={framework.id}
                icon={framework.icon}
                skillName={framework.name}
              />
            ))}
          </div>
        </section>

        <section className="container flex flex-col items-center">
          <h2 className="text-white text-center py-4 sm:py-8">
            Tools & Services
          </h2>
          <div className="grid grid-cols-4 gap-4 md:grid-cols-3">
            {Tools?.map((tool) => (
              <SkillTemplate
                key={tool.id}
                icon={tool.icon}
                skillName={tool.name}
              />
            ))}
          </div>
        </section>
      </div>
      <Footer />
    </div>
  );
}
