import Head from "next/head";
import {
  ApolloClient,
  InMemoryCache,
  createHttpLink,
  gql,
} from "@apollo/client";
import { setContext } from "@apollo/client/link/context";
import ReactTypingEffect from "react-typing-effect";

import { Header } from "@/components/header";
import { Footer } from "@/components/footer";
import { SkillTemplate } from "@/components/skilltemplate";
import { Projects } from "@/components/projects";

import { Languages } from "@/data/languages";
import { Libraries } from "@/data/libraries";
import { Frameworks } from "@/data/frameworks";
import { Tools } from "@/data/tools";

interface HomeProps {
  pinnedItems: any[];
}

export default function Home({ pinnedItems }: HomeProps) {
  return (
    <div className="bg-zinc-900 min-h-screen">
      <Head>
        <title>Shane Le's Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* Header */}
      <Header />
      {/* Hero Section */}
      <div className="mt-12 rounded-lg grid-cols-1 max-w-xs sm:max-w-md md:pt-8 md:max-w-2xl xl:max-w-6xl mx-auto">
        <div className="flex flex-col space-y-4  font-semibold text-center">
          {/* Hero Heading Text*/}
          <h1 className="text-3xl md:text-5xl text-rose-600">
            Hallo, I’m Shane! 👋
          </h1>
          <h2 className="text-3xl md:text-4xl text-mid text-white">
            <ReactTypingEffect
              typingDelay={200}
              speed={30}
              eraseSpeed={30}
              eraseDelay={1500}
              text={[`Frontend Developer`, `Gym-goer`, `Learner`, `Cat Lover`]}
            />
          </h2>
          {/* Hero Paragraph Text */}
          <p className="text-lg md:text-xl text-white">
            I love to design and build beautiful user-friendly websites and web
            applications.
          </p>
        </div>
      </div>
      {/* Technical Skills Section */}
      <h2 className="text-rose-600 text-center font-semibold text-2xl pt-6 sm:pt-12">
        Technical Skills
      </h2>
      <div className="sm:grid grid-cols-3 gap-4 md:max-w-4xl lg:max-w-7xl pt-3 pb-12  mx-auto">
        <section className="container flex flex-col items-center">
          <h2 className="text-white text-center py-4 sm:py-8">Languages</h2>
          <div className="grid grid-cols-4 gap-4 md:grid-cols-3">
            {Languages?.map((language) => (
              <SkillTemplate
                key={language.id}
                icon={language.icon}
                skillName={language.name}
                id={0}
              />
            ))}
          </div>
        </section>

        <section className="container flex flex-col items-center">
          <h2 className="text-white text-center py-4 sm:py-8">
            Libraries & Frameworks
          </h2>
          <div className="grid grid-cols-4 gap-4 md:grid-cols-3">
            {Libraries?.map((library) => (
              <SkillTemplate
                key={library.id}
                icon={library.icon}
                skillName={library.name}
                id={library.id}
              />
            ))}
            {Frameworks?.map((framework) => (
              <SkillTemplate
                key={framework.id}
                icon={framework.icon}
                skillName={framework.name}
                id={framework.id}
              />
            ))}
          </div>
        </section>

        <section className="container flex flex-col items-center">
          <h2 className="text-white text-center py-4 sm:py-8">
            Tools & Services
          </h2>
          <div className="grid grid-cols-4 gap-4 md:grid-cols-3">
            {Tools?.map((tool) => (
              <SkillTemplate
                key={tool.id}
                icon={tool.icon}
                skillName={tool.name}
                id={tool.id}
              />
            ))}
          </div>
        </section>
      </div>
      {/* Projects Section */}
      <h2 className="text-rose-600 text-center font-semibold text-2xl pt-6 sm:pt-12">
        Projects
      </h2>
      <Projects pinnedItems={pinnedItems} />
      {/* Footer */}
      <Footer />
    </div>
  );
}

export async function getStaticProps() {
  const httpLink = createHttpLink({
    uri: "https://api.github.com/graphql",
  });

  const authLink = setContext((_, { headers }) => {
    return {
      headers: {
        ...headers,
        authorization: `Bearer ${process.env.GITHUB_ACCESS_TOKEN}`,
      },
    };
  });

  const client = new ApolloClient({
    link: authLink.concat(httpLink),
    cache: new InMemoryCache(),
  });

  const { data } = await client.query({
    query: gql`
      {
        user(login: "shanedle") {
          id
          pinnedItems(first: 6) {
            edges {
              node {
                ... on Repository {
                  id
                  name
                  forkCount
                  stargazerCount
                  openGraphImageUrl
                  assignableUsers(first: 5) {
                    edges {
                      node {
                        id
                        avatarUrl
                        name
                      }
                    }
                  }
                  description
                  url
                  repositoryTopics(first: 5) {
                    edges {
                      node {
                        id
                        topic {
                          name
                        }
                      }
                    }
                  }
                  watchers {
                    totalCount
                  }
                  homepageUrl
                  object(expression: "main") {
                    ... on Commit {
                      id
                      history {
                        totalCount
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    `,
  });

  const { user } = data;
  const pinnedItems = user.pinnedItems.edges?.map((edge) => edge.node);

  return {
    props: {
      pinnedItems,
    },
  };
}
